FROM node:20-alpine AS build
WORKDIR /app
COPY customer-resolution-ui/package*.json ./
RUN npm ci
COPY customer-resolution-ui/ .
RUN npm run build

FROM nginx:alpine AS final
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
